n = input('Digite algo:')
print('O tipo primitivo desse valor é:', type(n))
print('É alfabético?', n.isalpha())
print('É um número?', n.isnumeric())
print('É alfanumérico?', n.isalnum())
print('Só tem espaço?', n.isspace())
print('É decimal?', n.isdecimal())
print('Esta em maiuscúlo?', n.isupper())
